# FROM ollama/ollama:0.5.12 AS base

FROM nvidia/cuda:12.8.1-base-ubuntu24.04
ENV OLLAMA_HOST=127.0.0.1:11435

RUN apt update
RUN apt upgrade -y
RUN apt install bash coreutils curl python3 python3-venv python3-pip perl pandoc poppler-utils -y
RUN apt clean && apt autoremove -y
RUN rm -rf /var/lib/apt/lists

RUN curl -fsSL https://ollama.com/install.sh | sh
RUN ollama serve & sleep 5; ollama pull aya-expanse:8b
RUN ollama serve & sleep 5; ollama pull aya-expanse:32b

RUN rm /usr/lib/python3.*/EXTERNALLY-MANAGED
RUN python3 -m pip install --no-cache-dir ollama argostranslate epubparser gradio

COPY argos_setup.py /babellica/argos_setup.py
RUN python3 /babellica/argos_setup.py

EXPOSE 7860
ENV GRADIO_SERVER_NAME="0.0.0.0"
ENV ARGOS_DEVICE_TYPE=auto
COPY . /babellica
WORKDIR /tmp
ENTRYPOINT ["python3"]
CMD ["/babellica/main.py", "--gradio"]

